import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import "./globals.css";

import { WalletProvider } from "@/config/wallet.config";
import MainLayout from "@/layout";


const inter = Inter({ subsets: ["latin"] });
const montserrat = Montserrat({subsets: ["latin"]})
export const metadata: Metadata = {
  title: "Marketplace NFT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <WalletProvider>{children}</WalletProvider>
      </body>
    </html>
  );
}
